/**
 * Generated by `gencow codegen`
 * Do not edit this file manually.
 *
 * Frontend-only — no backend dependency; safe to import from client bundles.
 * Procedure defs: `@gencow/client` (`defineProcedureQuery`, `defineProcedureMutation`).
 * Hooks: `@gencow/react` (`useQuery`, `useMutation`). Types from `./operations.d.ts`:
 *   defineProcedureQuery<Operations.NewTasksListOutput>("new-tasks.list", { allowAnonymous: true })
 *   defineProcedureMutation<Operations.TaskCustom4Output>("task.custom4")
 */
import { defineProcedureQuery, defineProcedureMutation } from "@gencow/client";
export const api = {
    articles: {
        get: defineProcedureQuery("articles.get", { allowAnonymous: true, realtime: "public", crudRealtime: { "kind": "get" } }),
        list: defineProcedureQuery("articles.list", { allowAnonymous: true, realtime: "public", crudRealtime: { "kind": "list" } }),
    },
    bookings: {
        create: defineProcedureMutation("bookings.create"),
        list: defineProcedureQuery("bookings.list"),
    },
    ebooks: {
        get: defineProcedureQuery("ebooks.get", { allowAnonymous: true, realtime: "public", crudRealtime: { "kind": "get" } }),
        list: defineProcedureQuery("ebooks.list", { allowAnonymous: true, realtime: "public", crudRealtime: { "kind": "list" } }),
        mySubscriptions: defineProcedureQuery("ebooks.mySubscriptions"),
        subscribe: defineProcedureMutation("ebooks.subscribe"),
        unsubscribe: defineProcedureMutation("ebooks.unsubscribe"),
    },
    healing: {
        history: defineProcedureQuery("healing.history"),
        measure: defineProcedureMutation("healing.measure"),
        recommend: defineProcedureQuery("healing.recommend"),
    },
    sellers: {
        apply: defineProcedureMutation("sellers.apply"),
        myApplication: defineProcedureQuery("sellers.myApplication"),
    },
    sites: {
        get: defineProcedureQuery("sites.get", { allowAnonymous: true, realtime: "public", crudRealtime: { "kind": "get" } }),
        list: defineProcedureQuery("sites.list", { allowAnonymous: true, realtime: "public", crudRealtime: { "kind": "list" } }),
    },
};
